//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdtK22CNTlession1006.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TdtAccount
    {
        public int TdtID { get; set; }
        public string TdtUserName { get; set; }
        public string TdtPassword { get; set; }
        public string TdtFullName { get; set; }
        public string TdtEmail { get; set; }
        public string TdtPhone { get; set; }
        public Nullable<bool> TdtActive { get; set; }
    }
}
